# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import trades.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.CharField(default=trades.utils.id_generator, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Sell Amount')),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Buy Amount')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Rate')),
                ('date_booked', models.DateTimeField(auto_now_add=True, verbose_name='Date Booked')),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='trades.Currencies', verbose_name='Buy Currency')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='trades.Currencies', verbose_name='Sell Currency')),
            ],
        ),
    ]
