# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100, verbose_name='Buy Amount'),
        ),
    ]
